networks:
  nifi_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24

services:
  zookeeper1:
    image: 'docker.io/bitnami/zookeeper:latest'
    hostname: zookeeper1
    container_name: zookeeper1
    # mem_limit: 1g
    # cpus: 0.5
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_MY_ID: 1
      ZOO_SERVER_ID: 1
      ZOO_SERVERS: "zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888"
    networks:
      nifi_network:
        ipv4_address: 192.168.0.11
    volumes:
      - zk_conf1:/conf
      - zk_data1:/bitnami      

  zookeeper2:
    image: 'docker.io/bitnami/zookeeper:latest'
    hostname: zookeeper2
    container_name: zookeeper2
    # mem_limit: 1g
    # cpus: 0.5
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_MY_ID: 2
      ZOO_SERVER_ID: 2
      ZOO_SERVERS: "zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888"
    networks:
      nifi_network:
        ipv4_address: 192.168.0.12
    volumes:
      - zk_conf2:/conf
      - zk_data2:/bitnami  

  zookeeper3:
    image: 'docker.io/bitnami/zookeeper:latest'
    hostname: zookeeper3
    container_name: zookeeper3
    # mem_limit: 1g
    # cpus: 0.5
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_MY_ID: 3
      ZOO_SERVER_ID: 3
      ZOO_SERVERS: "zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888"
    networks:
      nifi_network:
        ipv4_address: 192.168.0.13
    volumes:
      # - zk_data3:/data
      - zk_conf3:/conf
      - zk_data3:/bitnami 

  tls-toolkit:
    image: apache/nifi:1.28.1
    hostname: nifi-toolkit
    container_name: nifi-toolkit
    mem_limit: 1g
    cpus: 0.5
    entrypoint: ["bash", "-c", "/opt/nifi/nifi-toolkit-current/bin/tls-toolkit.sh standalone -O -o /opt/certs -n 'nifi1,nifi2,nifi3' -P password123 -K password123 -S password123 -B password123; chown -R nifi:nifi /opt/certs;chown -Rf nifi:nifi /opt/certs;ls /opt/certs/ -lrt"]
    volumes:
      - /home/user/ssl/nifi_certs:/opt/certs
    user: root
    networks:
      nifi_network:
        ipv4_address: 192.168.0.40

  nifi-registry:
    image: apache/nifi-registry:2.3.0
    hostname: nifi-registry
    container_name: nifi-registry
    mem_limit: 1g
    cpus: 0.5
    ports:
      - "18080:18080"
    networks:
      nifi_network:
        ipv4_address: 192.168.0.30

  nifi1:
    image: apache/nifi:2.3.0
    hostname: nifi1
    container_name: nifi1
    #mem_limit: 2g
    #cpus: 1.5
    user: nifi
    environment:
      NIFI_WEB_HTTPS_PORT: "8443"     
      NIFI_CLUSTER_IS_NODE: "true"
      NIFI_ZK_CONNECT_STRING: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
      NIFI_ELECTION_MAX_WAIT: "1 min"
      NIFI_ELECTION_MAX_CANDIDATES: 1
      NIFI_SENSITIVE_PROPS_KEY: "MySecureKey123!" 
      NIFI_CLUSTER_NODE_PROTOCOL_PORT: "9088"      
      NIFI_WEB_PROXY_HOST: "nifi1:8443,nifi1,nifi2:8443,nifi2,nifi3:8443,nifi3,localhost:8080"
      NIFI_STATE_MANAGEMENT_EMBEDDED_ZOOKEEPER_START: "false"   
      
      # Sécurisation des communications
      # NIFI_REMOTE_INPUT_SECURE: "true"     
      
      # Configuration de l'authentification
      SINGLE_USER_CREDENTIALS_USERNAME: "nifi"
      SINGLE_USER_CREDENTIALS_PASSWORD: "nifipassword"
      NIFI_SECURITY_USER_AUTHORIZER: "single-user-authorizer"
      NIFI_SECURITY_USER_LOGIN_IDENTITY_PROVIDER: "single-user-provider"
      INITIAL_ADMIN_IDENTITY: admin
      # Configuration TLS
      AUTH: "tls" 
      KEYSTORE_TYPE: "JKS" 
      KEYSTORE_PASSWORD: "password123"      
      KEY_PASSWORD: "password123"
      TRUSTSTORE_TYPE: "JKS"
      TRUSTSTORE_PASSWORD: "password123"
      # NIFI_CLUSTER_PROTOCOL_IS_SECURE: "true"   
      # NIFI_WEB_HTTPS_NETWORK_INTERFACE_DEFAULT: "" 
      
      NIFI_CLUSTER_ADDRESS: "nifi1"
      NIFI_CLUSTER_NODE_ADDRESS: "nifi1"
      NIFI_WEB_HTTPS_HOST: "nifi1"
      KEYSTORE_PATH: "/opt/certs/nifi1/keystore.jks"      
      TRUSTSTORE_PATH: "/opt/certs/nifi1/truststore.jks"
   
      # Configuration du Registry
      NIFI_REGISTRY_URL: "http://nifi-registry:18080"

    ports:
      - "8443:8443"
      - "9088:9088"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - nifi-registry     
      - tls-toolkit

    networks:
      nifi_network:
        ipv4_address: 192.168.0.21
    volumes:
      - nifi1_conf:/opt/nifi/nifi-current/conf
      - nifi1_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi1_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi1_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi1_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi1_state:/opt/nifi/nifi-current/state
      - nifi1_logs:/opt/nifi/nifi-current/logs
      - /home/user/ssl/nifi_certs:/opt/certs:ro
       
    entrypoint: >
      /bin/sh -c "
        sleep 10
        whoami
        # Démarrer NiFi
        /opt/nifi/scripts/start.sh"

  nifi2:
    image: apache/nifi:2.3.0
    hostname: nifi2
    container_name: nifi2
    user: nifi
    #mem_limit: 2g
    #cpus: 1.5
    environment:
      NIFI_WEB_HTTPS_PORT: "8443"     
      NIFI_CLUSTER_IS_NODE: "true"
      NIFI_ZK_CONNECT_STRING: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
      NIFI_ELECTION_MAX_WAIT: "1 min"
      NIFI_ELECTION_MAX_CANDIDATES: 1
      NIFI_SENSITIVE_PROPS_KEY: "MySecureKey123!" 
      NIFI_CLUSTER_NODE_PROTOCOL_PORT: "9088"      
      NIFI_WEB_PROXY_HOST: "nifi1:8443,nifi1,nifi2:8443,nifi2,nifi3:8443,nifi3,localhost:8080"
      NIFI_STATE_MANAGEMENT_EMBEDDED_ZOOKEEPER_START: "false"   
      
      # Sécurisation des communications
      # NIFI_REMOTE_INPUT_SECURE: "true"     
      
      # Configuration de l'authentification
      SINGLE_USER_CREDENTIALS_USERNAME: "nifi"
      SINGLE_USER_CREDENTIALS_PASSWORD: "nifipassword"
      NIFI_SECURITY_USER_AUTHORIZER: "single-user-authorizer"
      NIFI_SECURITY_USER_LOGIN_IDENTITY_PROVIDER: "single-user-provider"
      INITIAL_ADMIN_IDENTITY: admin
      # Configuration TLS
      AUTH: "tls" 
      KEYSTORE_TYPE: "JKS" 
      KEYSTORE_PASSWORD: "password123"      
      KEY_PASSWORD: "password123"
      TRUSTSTORE_TYPE: "JKS"
      TRUSTSTORE_PASSWORD: "password123"
      # NIFI_CLUSTER_PROTOCOL_IS_SECURE: "true"   
      # NIFI_WEB_HTTPS_NETWORK_INTERFACE_DEFAULT: "" 
      
      NIFI_CLUSTER_ADDRESS: "nifi2"
      NIFI_CLUSTER_NODE_ADDRESS: "nifi2"
      NIFI_WEB_HTTPS_HOST: "nifi2"
      KEYSTORE_PATH: "/opt/certs/nifi2/keystore.jks"      
      TRUSTSTORE_PATH: "/opt/certs/nifi2/truststore.jks"
   
      # Configuration du Registry
      NIFI_REGISTRY_URL: "http://nifi-registry:18080"

    ports:
      - "8444:8443"
      - "9089:9088"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - tls-toolkit
      - nifi-registry
    networks:
      nifi_network:
        ipv4_address: 192.168.0.22
    volumes:
      - nifi2_conf:/opt/nifi/nifi-current/conf
      - nifi2_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi2_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi2_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi2_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi2_state:/opt/nifi/nifi-current/state
      - nifi2_logs:/opt/nifi/nifi-current/logs
      - /home/user/ssl/nifi_certs:/opt/certs:ro
    entrypoint: >
      /bin/sh -c "
        sleep 10
        whoami       
        # Démarrer NiFi
        /opt/nifi/scripts/start.sh"

  nifi3:
    image: apache/nifi:2.3.0
    hostname: nifi3
    container_name: nifi3
    #mem_limit: 2g
    #cpus: 1.5
    user: nifi
    environment:
      NIFI_WEB_HTTPS_PORT: "8443"     
      NIFI_CLUSTER_IS_NODE: "true"
      NIFI_ZK_CONNECT_STRING: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
      NIFI_ELECTION_MAX_WAIT: "1 min"
      NIFI_ELECTION_MAX_CANDIDATES: 1
      NIFI_SENSITIVE_PROPS_KEY: "MySecureKey123!" 
      NIFI_CLUSTER_NODE_PROTOCOL_PORT: "9088"      
      NIFI_WEB_PROXY_HOST: "nifi1:8443,nifi1,nifi2:8443,nifi2,nifi3:8443,nifi3,localhost:8080"
      NIFI_STATE_MANAGEMENT_EMBEDDED_ZOOKEEPER_START: "false"   
      
      # Sécurisation des communications
      # NIFI_REMOTE_INPUT_SECURE: "true"     
      
      # Configuration de l'authentification
      SINGLE_USER_CREDENTIALS_USERNAME: "nifi"
      SINGLE_USER_CREDENTIALS_PASSWORD: "nifipassword"
      NIFI_SECURITY_USER_AUTHORIZER: "single-user-authorizer"
      NIFI_SECURITY_USER_LOGIN_IDENTITY_PROVIDER: "single-user-provider"
      INITIAL_ADMIN_IDENTITY: admin
      # Configuration TLS
      AUTH: "tls" 
      KEYSTORE_TYPE: "JKS" 
      KEYSTORE_PASSWORD: "password123"      
      KEY_PASSWORD: "password123"
      TRUSTSTORE_TYPE: "JKS"
      TRUSTSTORE_PASSWORD: "password123"
      # NIFI_CLUSTER_PROTOCOL_IS_SECURE: "true"   
      # NIFI_WEB_HTTPS_NETWORK_INTERFACE_DEFAULT: "" 
      
      NIFI_CLUSTER_ADDRESS: "nifi3"
      NIFI_CLUSTER_NODE_ADDRESS: "nifi3"
      NIFI_WEB_HTTPS_HOST: "nifi3"
      KEYSTORE_PATH: "/opt/certs/nifi3/keystore.jks"      
      TRUSTSTORE_PATH: "/opt/certs/nifi3/truststore.jks"
   
      # Configuration du Registry
      NIFI_REGISTRY_URL: "http://nifi-registry:18080"

    ports:
      - "8445:8443"
      - "9090:9088"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - tls-toolkit
      - nifi-registry
    networks:
      nifi_network:
        ipv4_address: 192.168.0.23
    volumes:
      - nifi3_conf:/opt/nifi/nifi-current/conf
      - nifi3_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi3_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi3_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi3_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi3_state:/opt/nifi/nifi-current/state
      - nifi3_logs:/opt/nifi/nifi-current/logs
      - /home/user/ssl/nifi_certs:/opt/certs:ro
    entrypoint: >
      /bin/sh -c "
        sleep 10
        whoami
        # Démarrer NiFi
        /opt/nifi/scripts/start.sh"

  mysql:
    image: mysql:latest
    hostname: mysql
    container_name: mysql
    # restart: always
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sampledb
    ports:
      - "3306:3306"
    networks:
      nifi_network:
        ipv4_address: 192.168.0.50
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  mysql-data:
    driver: local  
  nifi_certs:
    driver: local  
  zk_data1:
    driver: local
  zk_data2:
    driver: local  
  zk_data3:
    driver: local
  zk_conf1:
    driver: local
  zk_conf2:
    driver: local
  zk_conf3:
    driver: local
  certs:
    driver: local
  nifi1_conf:
    driver: local
  nifi1_content_repository:
    driver: local
  nifi1_database_repository:
    driver: local
  nifi1_flowfile_repository:
    driver: local
  nifi1_provenance_repository:
    driver: local
  nifi1_state:
    driver: local
  nifi1_logs:
    driver: local
  nifi2_conf:
    driver: local
  nifi2_content_repository:
    driver: local
  nifi2_database_repository:
    driver: local
  nifi2_flowfile_repository:
    driver: local
  nifi2_provenance_repository:
    driver: local
  nifi2_state:
    driver: local
  nifi2_logs:
    driver: local
  nifi3_conf:
    driver: local
  nifi3_content_repository:
    driver: local
  nifi3_database_repository:
    driver: local
  nifi3_flowfile_repository:
    driver: local
  nifi3_provenance_repository:
    driver: local
  nifi3_state:
    driver: local
  nifi3_logs:
    driver: local